# Generated by Django 4.2.6 on 2023-10-28 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapago',
            name='NombreFormaPago',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historialpago',
            name='IdUsuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.usuario'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Direccion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='IdUsuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.usuario'),
        ),
        migrations.AlterField(
            model_name='prevision',
            name='Cobertura',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prevision',
            name='Tramo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='Direccion',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='IdUsuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.usuario'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='CargoRol',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
